---
version: "3.9"
services:

  product-service: 
    image: igh9410/product-service:v2
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - broker
      - eureka-server
    environment:
      - KAFKA_BROKER_URL=broker:9092
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/java
      - EUREKA_URL=http://eureka-server:8070/eureka
    networks:
      - backend
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
  
  subscription-service:
    image: igh9410/subscription-service:v1
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    networks:
      - backend
  
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  eureka-server:
    image: igh9410/eureka-server:v1
    ports:
      - "8070:8070"
    networks:
      - backend

  api-gateway:
    image: igh9410/api-gateway:v1
    ports:
      - "8888:8888"
    networks:
      - backend  
  

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes: 
  mongodb_data:
