server:
  port: 5001
spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://localhost:3306/subscription_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: igh9410
    password: Rjsgur94!
  jpa:
    hibernate:
      ddl-auto: update
 # config:
  #  import: optional:configserver:http://localhost:8071
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

