server:
  port: 5000
logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
  file:
    name: "productservice.log"
spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Java
    rest:
      basePath: /api
 # config:
  #  import: optional:configserver:http://localhost:8071
   # use-legacy-processing: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka


